version: "3.3"

services:

  app:
    build:
      context: .
      dockerfile: ./_docker/php/Dockerfile
    image: dev_tarku
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    working_dir: /var/www/app
    user: ${UID}:${GID}
    ports:
      - ${APP_PORT}:9000
    command: ./_docker/php/run_server.sh
    volumes:
      - ./_docker/php/conf:/usr/local/etc/php
      - ./:/var/www/app
      - ./storage/logs:/var/www/app/storage/logs

  mysql:
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    hostname: mysql
    image: mysql:latest
    ports:
     - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./_data/mysql:/var/lib/mysql


  proxy:
    image: nginx:1.20
    container_name: ${PROXY_CONTAINER_NAME}
    restart: always
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./:/var/www/app
      - ./_docker/nginx:/etc/nginx/conf.d
    links:
      - app

  redis:
    image: redis:5.0-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: always
